// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebApp.Models.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Birth")
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("constacts");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Birth = new DateOnly(2000, 10, 10),
                            Category = 0,
                            Created = new DateTime(2024, 11, 6, 11, 39, 25, 28, DateTimeKind.Local).AddTicks(2422),
                            Email = "123@123",
                            FirstName = "123",
                            LastName = "123",
                            PhoneNumber = "123123123"
                        },
                        new
                        {
                            Id = 5,
                            Birth = new DateOnly(2000, 10, 10),
                            Category = 0,
                            Created = new DateTime(2024, 11, 6, 11, 39, 25, 28, DateTimeKind.Local).AddTicks(2463),
                            Email = "abc@abc",
                            FirstName = "abc",
                            LastName = "abc",
                            PhoneNumber = "123123124"
                        },
                        new
                        {
                            Id = 6,
                            Birth = new DateOnly(2000, 10, 10),
                            Category = 0,
                            Created = new DateTime(2024, 11, 6, 11, 39, 25, 28, DateTimeKind.Local).AddTicks(2465),
                            Email = "123@1235abc",
                            FirstName = "1235abc",
                            LastName = "1235abc",
                            PhoneNumber = "123123125"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
